# .travis.yml
dist: trusty

language: php

php:
  - 7.2

addons:
  mariadb: 10.1

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE restaurant-valdson;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit
